version: '3.9'
services:
  frontend:
        build: ./front-end
        container_name: app_frontend
        depends_on:
          backend:
            condition: service_healthy
        ports:
          - 3000:3000
        restart: 'always'
        healthcheck:
          test: ["CMD", "lsof", "-t", "-i:3000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
          timeout: 10s
          retries: 5
  backend:
    build: ./back-end
    container_name: app_backend
    links:
      - db
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
        PORT: 3001
        DATABASE_URL: "mysql://root:123456@db:3306/todo-list"
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
